# requiere: https://taskfile.dev/#/installation
version: "3"

vars:
    PROJECT_PATH: "{{.PWD}}"
    # ENV: prod or dev
    ENV: dev

dotenv: ["{{.PROJECT_PATH}}/config/environments/{{.ENV}}/.env"]

tasks:
    app.up:
        desc: "Start app service in background mode. Usage: task app.up"
        cmds:
            - sudo docker-compose --env-file {{.PROJECT_PATH}}/config/environments/{{.ENV}}/.env up

    app.down:
        desc: "Stop app service. Usage: task app.down"
        cmds:
            - sudo docker-compose down

    docker.build:
        desc: "Build the docker image. Usage: task docker.build"
        cmds:
            - sudo docker build -t {{.APP_CONTAINER_NAME}}  .

    build:
        desc: "Build app binary file in bin folder. Usage: task build"
        cmds:
            - GOFLAGS=-mod=mod go build -o bin/{{.APP_NAME}} main.go

    swagger:
        desc: Swagger documentation
        cmds:
            - sudo docker run -i yousan/swagger-yaml-to-html < swagger/swagger.yml > doc/api.html
